### ISSUE TITLE
文件名带 # 特殊字符 会报错

### ISSUE THREAD

**Issue by wdyggh** [comwrg/bilibiliupload#26]
有时上传的文件名中带特殊字符的 比如 #     就会报错。

**Comment by comwrg** [comment]
报错信息?

**Comment by wdyggh** [comment]
```
Login: True
Traceback (most recent call last):
  File " uploadtest.py", line 158, in <module>
    b.upload(parts=videoPart, title=title, tid=tid, tag=tags, desc=videofile+decad, source='aaa‘)
  File "D:\Anaconda3\lib\site-packages\bilibiliupload\bilibili.py", line 221, in upload
    json = r.json()
  File "D:\Anaconda3\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Anaconda3\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "D:\Anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Anaconda3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[Finished in 1.7s with exit code 1]
```
大概是这样的

**Comment by wdyggh** [comment]
？？？
