### ISSUE TITLE
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

### ISSUE THREAD

**Issue by kaidiren** [comwrg/bilibiliupload#28]
```
0/458 MULTIPART_PUT_SUCCESS
1/458 MULTIPART_PUT_SUCCESS
2/458 MULTIPART_PUT_SUCCESS
3/458 MULTIPART_PUT_SUCCESS
4/458 MULTIPART_PUT_SUCCESS
Traceback (most recent call last):
  File "/root/B/bili/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/root/B/bili/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/root/B/bili/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/python/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/python/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/B/bili/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/root/B/bili/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/root/B/bili/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/B/bili/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/root/B/bili/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/root/B/bili/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/root/B/bili/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/python/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/python/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/B/bili/bilibili-live-record-and-upload/upload.py", line 67, in <module>
    b.upload(parts, title, tid, tag, desc)
  File "/root/B/bili/lib/python3.6/site-packages/bilibiliupload/bilibili.py", line 280, in upload
    r = retry_upload_chunk()
  File "/root/B/bili/lib/python3.6/site-packages/bilibiliupload/bilibili.py", line 273, in retry_upload_chunk
    r = upload_chunk()
  File "/root/B/bili/lib/python3.6/site-packages/bilibiliupload/bilibili.py", line 266, in upload_chunk
    chunks_data,
  File "/root/B/bili/lib/python3.6/site-packages/requests/sessions.py", line 593, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/root/B/bili/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/B/bili/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/root/B/bili/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

```

**Comment by kaidiren** [comment]
貌似把这个异常给捕获了重试下就可以了，我对 requests 你看看知道不

**Comment by comwrg** [comment]
你可以自己写个重试机制, 这个是B站服务器把连接给切断了

**Comment by kaidiren** [comment]
你意思是他这个是直接把 session 都给切断了么？

**Comment by comwrg** [comment]
tcp的连接, 你写个`try`就可以了

**Comment by kaidiren** [comment]
ok
