### ISSUE TITLE
貌似B站接口升级啦，脚本上传报错

### ISSUE THREAD

**Issue by qazwsdc** [comwrg/bilibiliupload#32]
昨天还是好用的，刚刚试了下就不行了。
以下为报错代码：

0/3 MULTIPART_PUT_SUCCESS
1/3 MULTIPART_PUT_SUCCESS
2/3 MULTIPART_PUT_SUCCESS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/bilibiliupload/bilibili.py", line 338, in upload
    r = retry_add()
  File "/usr/local/lib/python3.6/dist-packages/bilibiliupload/bilibili.py", line 334, in retry_add
    raise Exception('Fail to add video, {}'.format(r.text))
Exception: Fail to add video, {"code":21111,"message":"系统升级中，提交失败，敬请谅解","ttl":1}

**Comment by jackforlit** [comment]
问题解决了吗？
话说在页面上上传文件也报这个错！！

**Comment by qianghuohhh** [comment]
现在我也报这个错，大大是怎么解决的啊？
