### ISSUE TITLE
{"code":21001,"message":"参数错误","ttl":1}

### ISSUE THREAD

**Issue by kaidiren** [comwrg/bilibiliupload#45]
```
DEBUG:bilibiliupload.bilibili:MULTIPART_PUT_SUCCESS
INFO:bilibiliupload.bilibili:upload part 58/62
DEBUG:urllib3.connectionpool:https://upos-sz-upcdnws.bilivideo.com:443 "PUT /ugc/m191218ws13i45pqcrmywj30kycj84cq.mp4?partNumber=60&uploadId=e2eb91dd3852762b19ed7c3ee1ed5486&chunk=59&chunks=62&size=8388608&start=494927872&end=503316480&total=519703918 HTTP/1.1" 200 None
DEBUG:bilibiliupload.bilibili:MULTIPART_PUT_SUCCESS
INFO:bilibiliupload.bilibili:upload part 59/62
DEBUG:urllib3.connectionpool:https://upos-sz-upcdnws.bilivideo.com:443 "PUT /ugc/m191218ws13i45pqcrmywj30kycj84cq.mp4?partNumber=61&uploadId=e2eb91dd3852762b19ed7c3ee1ed5486&chunk=60&chunks=62&size=8388608&start=503316480&end=511705088&total=519703918 HTTP/1.1" 200 None
DEBUG:bilibiliupload.bilibili:MULTIPART_PUT_SUCCESS
INFO:bilibiliupload.bilibili:upload part 60/62
DEBUG:urllib3.connectionpool:https://upos-sz-upcdnws.bilivideo.com:443 "PUT /ugc/m191218ws13i45pqcrmywj30kycj84cq.mp4?partNumber=62&uploadId=e2eb91dd3852762b19ed7c3ee1ed5486&chunk=61&chunks=62&size=7998830&start=511705088&end=519703918&total=519703918 HTTP/1.1" 200 None
DEBUG:bilibiliupload.bilibili:MULTIPART_PUT_SUCCESS
INFO:bilibiliupload.bilibili:upload part 61/62
DEBUG:urllib3.connectionpool:https://upos-sz-upcdnws.bilivideo.com:443 "POST /ugc/m191218ws13i45pqcrmywj30kycj84cq.mp4?output=json&name=20191218_030749_%E4%BB%A5%E6%92%92%E7%9A%84%E7%BB%93%E5%90%88.mp4&profile=ugcupos%2Fyb&uploadId=e2eb91dd3852762b19ed7c3ee1ed5486&biz_id=136406735 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: member.bilibili.com
DEBUG:urllib3.connectionpool:https://member.bilibili.com:443 "POST /x/vu/web/add?csrf=d41311322a81794d29a2fd7420cce050 HTTP/1.1" 200 47
DEBUG:bilibiliupload.bilibili:{"code":21001,"message":"参数错误","ttl":1}
ERROR:root:Traceback (most recent call last):
  File "upload.py", line 88, in <module>
    b.upload(parts, title, tid, tag, desc, source='', cover='', no_reprint=1, dynamic='', dtime=dtime, open_elec=False, max_retry=60)
  File "/usr/local/lib/python3.6/dist-packages/bilibiliupload/bilibili.py", line 361, in upload
    r = retry_add()
  File "/usr/local/lib/python3.6/dist-packages/bilibiliupload/bilibili.py", line 356, in retry_add
    raise Exception('Fail to add video, {}'.format(r.text))
Exception: Fail to add video, {"code":21001,"message":"参数错误","ttl":1}

```

版本 bilibiliupload (0.1.9)

**Comment by kaidiren** [comment]
报错：
```
b.upload(parts, title, tid, tag, desc, source='', cover='', no_reprint=1, dynamic='', dtime=dtime, open_elec=False, max_retry=60)


成功：
```
 b.upload(parts, title, tid, tag, desc, source='', cover='', no_reprint=1, dynamic='', dtime=dtime)
```

**Comment by comwrg** [comment]
`open_elec=False` 在v0.1.9应要写成`open_elec=0`。
