### ISSUE TITLE
长时间上传视频后，会出现OSError错误

### ISSUE THREAD

**Issue by jackforlit** [comwrg/bilibiliupload#48]
**Describe the bug**
如题

**Debug log**
2019-12-30 08:56:23,908 - DEBUG - Traceback (most recent call last):
  File "uploadToBilibili.py", line 89, in BiliBili_Upload
  File "lib\site-packages\bilibiliupload\bilibili.py", line 112, in login
  File "lib\site-packages\bilibiliupload\bilibili.py", line 98, in getkey
  File "lib\site-packages\requests\sessions.py", line 581, in post
  File "lib\site-packages\requests\sessions.py", line 533, in request
  File "lib\site-packages\requests\sessions.py", line 646, in send
  File "lib\site-packages\requests\adapters.py", line 416, in send
  File "lib\site-packages\requests\adapters.py", line 228, in cert_verify
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: C:\Users\ADMINI~1\AppData\Local\Temp\_MEI181962\certifi\cacert.pem

**Comment by comwrg** [comment]
经常出现吗？可以尝试换一台机子试试。

**Comment by jackforlit** [comment]
每2到3天出现一次吧。

**Comment by comwrg** [comment]
尝试
```python
b = Bilibili()
b.session.verify = False # 加入这一行，关闭https验证

```

**Comment by jackforlit** [comment]
好的，我试试
