### ISSUE TITLE
上传出错

### ISSUE THREAD

**Issue by btrspg** [comwrg/bilibiliupload#65]
你好，在使用该包上传视频时后出错

```
<Response [403]>
<class 'requests.models.Response'>
Traceback (most recent call last):
  File "video_uploads.py", line 57, in <module>
    defopt.run(upload_video)
  File "/Users/logan/opt/anaconda3/envs/test/lib/python3.7/site-packages/defopt.py", line 167, in run
    return _call_function(parser, args._func, args)
  File "/Users/logan/opt/anaconda3/envs/test/lib/python3.7/site-packages/defopt.py", line 511, in _call_function
    return func(*positionals, **keywords)
  File "video_uploads.py", line 50, in upload_video
    b.upload(videopart, title,122,tags,des,cover=cover,max_retry=5)
  File "/Users/logan/opt/anaconda3/envs/test/lib/python3.7/site-packages/bilibiliupload/bilibili.py", line 259, in upload
    json = r.json()
  File "/Users/logan/opt/anaconda3/envs/test/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/logan/opt/anaconda3/envs/test/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Users/logan/opt/anaconda3/envs/test/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/logan/opt/anaconda3/envs/test/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

我打印了`r`值，发现如下：
```
print(r)
<Response [403]>
print(type(r))
<class 'requests.models.Response'>
```

麻烦了

**Comment by JIA-Jimmy** [comment]
我也出现了这个问题
