### ISSUE TITLE
登录接口貌似彻底挂了

### ISSUE THREAD

**Issue by qazwsdc** [comwrg/bilibiliupload#67]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\XY\Downloads\bilibiliupload-master\bilibiliupload\bilibili.py", line 144, in login
    json = r.json()
  File "C:\Users\XY\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\XY\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\XY\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\XY\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jackforlit** [comment]
试下用cookie登录吧，不过最近上传好像又出问题了。。

**Comment by qazwsdc** [comment]
> 试下用cookie登录吧，不过最近上传好像又出问题了。。

能给个示例吗

**Comment by jackforlit** [comment]
> > 试下用cookie登录吧，不过最近上传好像又出问题了。。
> 
> 能给个示例吗

b = Bilibili('你的Cookie')
